import '../models/research_model.dart';

class ResearchService {
  Future<ResearchResult> analyzeResearch(String topic) async {
    // This is where API integration will happen in future
    // For now, return mock data
    
    await Future.delayed(Duration(seconds: 2)); // Simulate API call

    return ResearchResult(
      topic: topic,
      summary: 'This is a sample research summary. In future, this will be generated by AI APIs.',
      methodology: 'Sample methodology - AI analysis and data processing',
      findings: 'Sample findings - Research shows promising results',
      date: DateTime.now(),
    );
  }

  Future<List<ResearchResult>> getResearchHistory() async {
    // Mock history data
    return [
      ResearchResult(
        topic: 'Climate Change Impact',
        summary: 'Analysis of climate effects',
        methodology: 'AI modeling',
        findings: 'Significant impacts observed',
        date: DateTime.now().subtract(Duration(days: 1)),
      ),
      ResearchResult(
        topic: 'AI in Healthcare',
        summary: 'Medical AI applications',
        methodology: 'Case studies',
        findings: 'Improved diagnosis accuracy',
        date: DateTime.now().subtract(Duration(days: 3)),
      ),
    ];
  }
}
