import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// 📄 ReportAI —
/// تمام AI ماڈیولز کے نتائج کو merge کر کے مکمل PDF ریسرچ رپورٹ تیار کرتا ہے۔
class ReportAI {
  /// 🔹 Step 1: ڈیٹا merge + report text generate
  static Future<Map<String, dynamic>> generateCompleteReport({
    required String topic,
    required String hypothesis,
    required String researchSummary,
    required dynamic labResults,
    required dynamic medicalAnalysis,
    required dynamic treatmentPlan,
    required dynamic biologicalFindings,
  }) async {
    debugPrint('🧾 [ReportAI] Generating full research report for: $topic');

    // Combined textual summary
    final reportText = '''
📘 AI Medical Research Report
──────────────────────────────
🧠 Topic: $topic
💡 Hypothesis: $hypothesis

📖 Research Summary:
${researchSummary.isNotEmpty ? researchSummary : 'No research summary available.'}

🧪 Lab Testing Results:
${labResults.toString()}

📊 Medical Analysis:
${medicalAnalysis.toString()}

💊 Treatment Plan:
${treatmentPlan.toString()}

🧬 Biological Findings:
${biologicalFindings.toString()}

──────────────────────────────
📅 Generated by AI Trio System
''';

    // Generate PDF and save it
    final pdfPath = await _generatePDF(topic, reportText);

    return {
      'summary': reportText,
      'pdfPath': pdfPath,
    };
  }

  /// 🔹 Step 2: PDF Generator — Creates PDF file from given text
  static Future<String> _generatePDF(String topic, String reportText) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.all(24),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text('🔬 AI Medical Research Report',
                style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
          ),
          pw.Paragraph(text: reportText),
          pw.Divider(),
          pw.Text(
            'Generated by AI Research System',
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final outputDir = await getApplicationDocumentsDirectory();
    final filePath =
        '${outputDir.path}/report_${topic.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf';

    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    debugPrint('✅ PDF generated successfully at: $filePath');
    return filePath;
  }

  /// 🔹 نیا میتھڈ: discovery_screen.dart کے لیے compat میتھڈ
  static Future<String> generatePDFReport({
    required String language,
    required dynamic context,
  }) async {
    // فی الحال mock implementation
    debugPrint('📄 Generating PDF for language: $language');
    await Future.delayed(Duration(seconds: 2));
    
    final outputDir = await getApplicationDocumentsDirectory();
    final filePath = '${outputDir.path}/report_${DateTime.now().millisecondsSinceEpoch}.pdf';
    
    // Mock PDF file بنائیں
    final file = File(filePath);
    await file.writeAsString('Mock PDF content for $language');
    
    return filePath;
  }
}
