import 'dart:convert';
import 'package:flutter/foundation.dart';
import '../models/research_model.dart';
import '../utils/pdf_generator.dart';

/// 🧠 ReportAI —
/// یہ ماڈیول تمام AI ماڈیولز کے نتائج لے کر انہیں
/// ایک مکمل رپورٹ اور PDF میں تبدیل کرتا ہے۔
class ReportAI {
  /// 🔹 مکمل رپورٹ بنانا (Text + PDF دونوں)
  static Future<Map<String, dynamic>> generateCompleteReport({
    required String topic,
    required String hypothesis,
    required String researchSummary,
    required dynamic labResults,
    required dynamic medicalAnalysis,
    required dynamic treatmentPlan,
    required dynamic biologicalFindings,
  }) async {
    try {
      debugPrint("🧩 [ReportAI] Generating full report for $topic...");

      // Step 1: Text Summary تیار کرنا
      final StringBuffer reportBuffer = StringBuffer();
      reportBuffer.writeln("🧬 AI Research Report");
      reportBuffer.writeln("==============================\n");
      reportBuffer.writeln("Topic: $topic\n");
      reportBuffer.writeln("Hypothesis: $hypothesis\n");
      reportBuffer.writeln("Research Summary:\n$researchSummary\n");
      reportBuffer.writeln("Lab Results:\n${jsonEncode(labResults)}\n");
      reportBuffer.writeln("Medical Analysis:\n${jsonEncode(medicalAnalysis)}\n");
      reportBuffer.writeln("Treatment Plan:\n${jsonEncode(treatmentPlan)}\n");
      reportBuffer.writeln("Biological Findings:\n${jsonEncode(biologicalFindings)}\n");
      reportBuffer.writeln("==============================\n");
      reportBuffer.writeln("📅 Generated by AI Researcher at ${DateTime.now()}");

      final textReport = reportBuffer.toString();

      // Step 2: PDF تیار کرنا
      final pdfPath = await PdfGenerator.generateResearchPDF(
        research: MedicalResearch(
          id: DateTime.now().millisecondsSinceEpoch.toString(),
          topic: topic,
          hypothesis: hypothesis,
          methodology: "AI Orchestrated Multi-Agent Research",
          labResults: labResults,
          analysis: medicalAnalysis,
          conclusion: "AI-generated comprehensive report",
          pdfReport: "",
          createdAt: DateTime.now(),
          isAIResearch: true,
          aiDiscoveryData: {
            "summary": researchSummary,
            "lab": labResults,
            "analysis": medicalAnalysis,
            "cure": treatmentPlan,
            "bio": biologicalFindings,
          },
        ),
        reportText: textReport,
      );

      // Step 3: مکمل ڈیٹا ریٹرن
      final Map<String, dynamic> result = {
        "summary": textReport,
        "pdf": pdfPath,
      };

      debugPrint("✅ [ReportAI] Report generated successfully!");
      return result;
    } catch (e, st) {
      debugPrint("❌ [ReportAI] Error generating report: $e\n$st");
      return {
        "summary": "Error generating report",
        "pdf": null,
      };
    }
  }

  /// ⚙️ صرف PDF رپورٹ بنانا (اگر پہلے سے Text موجود ہو)
  static Future<String> generatePDFReport({
    required MedicalResearch research,
    required String reportText,
  }) async {
    try {
      final pdfPath = await PdfGenerator.generateResearchPDF(
        research: research,
        reportText: reportText,
      );
      return pdfPath;
    } catch (e) {
      debugPrint("❌ [ReportAI] Failed to generate PDF: $e");
      return '';
    }
  }
}
