import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// 📄 ReportAI —
/// تمام AI ماڈیولز کے نتائج کو merge کر کے مکمل PDF ریسرچ رپورٹ تیار کرتا ہے۔
class ReportAI {
  /// 🔹 Step 1: ڈیٹا merge + report text generate
  static Future<Map<String, dynamic>> generateCompleteReport({
    required String topic,
    required String hypothesis,
    required String researchSummary,
    required Map<String, dynamic> labResults,
    required Map<String, dynamic> medicalAnalysis,
    required Map<String, dynamic> treatmentPlan,
    required Map<String, dynamic> biologicalFindings,
  }) async {
    debugPrint('🧾 [ReportAI] Generating full research report for: $topic');

    // Combined textual summary
    final reportText = '''
📘 AI Medical Research Report
──────────────────────────────
🧠 Topic: $topic
💡 Hypothesis: $hypothesis

📖 Research Summary:
${researchSummary.isNotEmpty ? researchSummary : 'No research summary available.'}

🧪 Lab Testing Results:
${labResults['labFindings'] ?? labResults['results'] ?? 'No lab data available.'}

📊 Medical Analysis:
${medicalAnalysis['keyInsights'] ?? medicalAnalysis['insights'] ?? 'No analysis data available.'}

💊 Treatment Plan:
${treatmentPlan['treatmentName'] ?? 'Unnamed Treatment'} — ${treatmentPlan['method'] ?? 'No method described.'}

🧬 Biological Findings:
${biologicalFindings['biologicalFactors'] ?? biologicalFindings['summary'] ?? 'No biological data available.'}

──────────────────────────────
📅 Generated by AI Trio System
''';

    // Generate PDF and save it
    final pdfPath = await _generatePDF(topic, reportText);

    return {
      'summary': reportText,
      'pdf': pdfPath,
    };
  }

  /// 🔹 Step 2: PDF Generator — Creates PDF file from given text
  static Future<String> _generatePDF(String topic, String reportText) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.all(24),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text('🔬 AI Medical Research Report',
                style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
          ),
          pw.Paragraph(text: reportText),
          pw.Divider(),
          pw.Text(
            'Generated by AI Research System',
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final outputDir = await getApplicationDocumentsDirectory();
    final filePath =
        '${outputDir.path}/report_${topic.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf';

    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    debugPrint('✅ PDF generated successfully at: $filePath');
    return filePath;
  }
}
