import 'package:flutter/foundation.dart';
import '../models/research_model.dart';
import 'research_ai.dart';
import 'lab_testing_ai.dart';
import 'medanalyzer_ai.dart';
import 'curesynth_ai.dart';
import 'biomind_ai.dart';
import 'report_ai.dart';

/// 🎯 TrioOrchestrator —
/// مختلف AI ماڈیولز کو آپس میں coordinate کر کے مکمل رپورٹ تیار کرتا ہے۔
class TrioOrchestrator {
  /// 🔬 مرکزی فنکشن جو تمام AI مراحل چلاتا ہے
  static Future<MedicalResearch> runFullResearchPipeline({
    required String topic,
    required String hypothesis,
  }) async {
    debugPrint('🧠 Starting AI Research Pipeline for $topic');

    // ✅ Step 1: بنیادی تحقیق
    final researchData = await ResearchAI.createSummary(
      topic: topic,
      hypothesis: hypothesis,
    );

    // ✅ Step 2: لیب اینالیسس
    final labResults = await LabTestingAI.analyzeData(
      researchSummary: researchData['summary'] ?? '',
    );

    // ✅ Step 3: میڈیکل اینالیسز
    final analysis = await MedAnalyzerAI.extractInsights(
      labData: labResults,
    );

    // ✅ Step 4: علاج کی تجاویز
    final curePlan = await CureSynthAI.generateTreatmentPlan(
      analysis: analysis,
    );

    // ✅ Step 5: بائیولوجیکل تحقیق
    final bioFindings = await BioMindAI.runBiologicalResearch(
      topic: topic,
      relatedAnalysis: analysis,
    );

    // ✅ Step 6: رپورٹ تیار کرنا
    final reportData = await ReportAI.generateCompleteReport(
      topic: topic,
      hypothesis: hypothesis,
      researchSummary: researchData['summary'] ?? '',
      labResults: labResults,
      medicalAnalysis: analysis,
      treatmentPlan: curePlan,
      biologicalFindings: bioFindings,
    );

    // ✅ مکمل MedicalResearch object
    final research = MedicalResearch(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      topic: topic,
      hypothesis: hypothesis,
      methodology: 'AI-Orchestrated Multi-Agent Pipeline',
      labResults: labResults,
      analysis: analysis,
      conclusion: reportData['summary'] ?? 'Generated by AI',
      pdfReport: reportData['pdfPath'] ?? '',
      createdAt: DateTime.now(),
      isAIResearch: true,
      aiDiscoveryData: {
        'ResearchAI': researchData,
        'LabTestingAI': labResults,
        'MedAnalyzerAI': analysis,
        'CureSynthAI': curePlan,
        'BioMindAI': bioFindings,
      },
    );

    debugPrint('✅ Research pipeline completed successfully.');
    return research;
  }

  /// 🧩 پرانے کوڈز کے لیے compat method
  static Future<MedicalResearch> conductFullResearch(String topic) async {
    return await runFullResearchPipeline(
      topic: topic,
      hypothesis: 'Auto-generated hypothesis for $topic',
    );
  }
}
