import 'package:flutter/foundation.dart';
import '../models/research_model.dart';
import 'research_ai.dart';
import 'lab_testing_ai.dart';
import 'medanalyzer_ai.dart';
import 'curesynth_ai.dart';
import 'biomind_ai.dart';
import 'report_ai.dart';

/// 🎯 TrioOrchestrator —
/// یہ کلاس مختلف AI ماڈیولز کے درمیان کام کو تقسیم کرتی ہے اور
/// تمام data کو ایک مکمل research رپورٹ میں merge کر دیتی ہے۔
class TrioOrchestrator {
  /// 🔬 مکمل ریسرچ چلانے کا مرکزی فنکشن
  static Future<MedicalResearch> runFullResearchPipeline({
    required String topic,
    required String hypothesis,
  }) async {
    debugPrint('🧠 [TrioOrchestrator] Starting research pipeline for: $topic');

    // Step 1: Research AI — موضوع کی بنیادی تحقیق
    final researchData = await ResearchAI.generateResearchSummary(
      topic: topic,
      hypothesis: hypothesis,
    );

    // Step 2: Lab Testing AI — نتائج کا سائنسی تجزیہ
    final labResults = await LabTestingAI.runLabAnalysis(
      researchSummary: researchData['summary'],
    );

    // Step 3: MedAnalyzer — میڈیکل تشخیص اور مشاہدات
    final analysis = await MedAnalyzerAI.generateMedicalInsights(
      labData: labResults,
    );

    // Step 4: CureSynth — علاج یا تھراپی کی تجاویز
    final curePlan = await CureSynthAI.generateTreatmentPlan(
      analysis: analysis,
    );

    // Step 5: BioMind — حیاتیاتی پہلوؤں کی گہری تحقیق
    final bioFindings = await BioMindAI.runBiologicalResearch(
      topic: topic,
      relatedAnalysis: analysis,
    );

    // Step 6: Report AI — تمام data کو merge کر کے ایک جامع رپورٹ تیار کرنا
    final reportData = await ReportAI.generateCompleteReport(
      topic: topic,
      hypothesis: hypothesis,
      researchSummary: researchData['summary'],
      labResults: labResults,
      medicalAnalysis: analysis,
      treatmentPlan: curePlan,
      biologicalFindings: bioFindings,
    );

    // Final: Complete object build
    final research = MedicalResearch(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      topic: topic,
      hypothesis: hypothesis,
      methodology: 'Multi-AI Orchestrated Research Pipeline',
      labResults: labResults,
      analysis: analysis,
      conclusion: reportData['summary'] ?? 'Result generated by AI',
      pdfReport: reportData['pdf'] ?? '',
      createdAt: DateTime.now(),
      isAIResearch: true,
      aiDiscoveryData: {
        'ResearchAI': researchData,
        'LabTestingAI': labResults,
        'MedAnalyzerAI': analysis,
        'CureSynthAI': curePlan,
        'BioMindAI': bioFindings,
      },
    );

    debugPrint('✅ [TrioOrchestrator] Research pipeline complete for: $topic');
    return research;
  }
}
