import 'package:flutter/foundation.dart';
import '../models/research_model.dart';
import 'research_ai.dart';
import 'lab_testing_ai.dart';
import 'medanalyzer_ai.dart';
import 'curesynth_ai.dart';
import 'biomind_ai.dart';
import 'report_ai.dart';

/// 🎯 TrioOrchestrator —
/// مختلف AI ماڈیولز کو آپس میں coordinate کر کے مکمل رپورٹ تیار کرتا ہے۔
class TrioOrchestrator {
  /// 🔬 مرکزی فنکشن جو تمام AI مراحل چلاتا ہے
  static Future<MedicalResearch> runFullResearchPipeline({
    required String topic,
    required String hypothesis,
  }) async {
    debugPrint('🧠 Starting AI Research Pipeline for $topic');

    // ✅ Step 1: بنیادی تحقیق - درست میتھڈ نام
    final researchData = await ResearchAI.generateResearchSummary(
      topic: topic,
    );

    // ✅ Step 2: لیب اینالیسس - درست میتھڈ نام
    final labResults = await LabTestingAI.runLabAnalysis(
      researchData: researchData,
    );

    // ✅ Step 3: میڈیکل اینالیسز - درست میتھڈ نام
    final analysis = await MedAnalyzerAI.generateMedicalInsights(
      labResults: labResults,
      topic: topic,
    );

    // ✅ Step 4: علاج کی تجاویز - درست parameters
    final curePlan = await CureSynthAI.generateTreatmentPlan(
      medicalProblem: topic,
      analysisData: analysis,
    );

    // ✅ Step 5: بائیولوجیکل تحقیق - درست میتھڈ نام
    final bioFindings = await BioMindAI.runBiologicalResearch(
      topic: topic,
      medicalData: analysis,
    );

    // ✅ Step 6: رپورٹ تیار کرنا - درست parameters
    final reportData = await ReportAI.generateCompleteReport(
      topic: topic,
      hypothesis: hypothesis,
      researchSummary: researchData['summary'] ?? researchData.toString(),
      labResults: labResults,
      medicalAnalysis: analysis,
      treatmentPlan: curePlan,
      biologicalFindings: bioFindings,
    );

    // ✅ مکمل MedicalResearch object
    final research = MedicalResearch(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      topic: topic,
      hypothesis: hypothesis,
      methodology: 'AI-Orchestrated Multi-Agent Pipeline',
      labResults: labResults.toString(),
      analysis: analysis.toString(),
      conclusion: reportData['summary'] ?? 'Generated by AI',
      pdfReport: reportData['pdfPath'] ?? '',
      createdAt: DateTime.now(),
      isAIResearch: true,
      aiDiscoveryData: {
        'research_ai': researchData,
        'lab_ai': labResults,
        'stats_ai': analysis,
        'treatment_ai': curePlan,
        'bio_ai': bioFindings,
      },
    );

    debugPrint('✅ Research pipeline completed successfully.');
    return research;
  }

  /// 🧩 پرانے کوڈز کے لیے compat method
  static Future<MedicalResearch> conductFullResearch(String topic) async {
    return await runFullResearchPipeline(
      topic: topic,
      hypothesis: 'Auto-generated hypothesis for $topic',
    );
  }
}
