import 'package:intl/intl.dart';

/// 🌐 LanguageUtils
/// یہ کلاس مختلف زبانوں کے لیے PDF headings، labels اور تاریخ کو فارمیٹ کرنے کے لیے استعمال ہوتی ہے۔
class LanguageUtils {
  /// 🏷️ PDF Headers (تمام زبانوں کے لیے)
  static Map<String, String> getPDFHeaders(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return {
          'title': 'تحقیقاتی رپورٹ',
          'topic': 'موضوع',
          'date': 'تاریخ',
          'hypothesis': 'تحقیقی مفروضہ',
          'methodology': 'تحقیقی طریقہ کار',
          'labResults': 'لیب کے نتائج',
          'conclusion': 'نتیجہ و تجزیہ',
          'footer': 'رپورٹ کا اختتام — تیار کردہ AI Trio Research System',
        };

      case 'arabic':
        return {
          'title': 'تقرير البحث العلمي',
          'topic': 'الموضوع',
          'date': 'التاريخ',
          'hypothesis': 'الفرضية',
          'methodology': 'المنهجية',
          'labResults': 'نتائج المختبر',
          'conclusion': 'الاستنتاج والتحليل',
          'footer': 'نهاية التقرير — تم توليده بواسطة نظام أبحاث AI Trio',
        };

      default:
        return {
          'title': 'Research Report',
          'topic': 'Topic',
          'date': 'Date',
          'hypothesis': 'Hypothesis',
          'methodology': 'Methodology',
          'labResults': 'Lab Results',
          'conclusion': 'Conclusion & Analysis',
          'footer': 'End of Report — Generated by AI Trio Research System',
        };
    }
  }

  /// 📅 تاریخ کو لوکل زبان میں فارمیٹ کرے
  static String formatDate(DateTime date, String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return DateFormat('dd MMMM yyyy', 'ur').format(date);
      case 'arabic':
        return DateFormat('dd MMMM yyyy', 'ar').format(date);
      default:
        return DateFormat('MMMM dd, yyyy', 'en').format(date);
    }
  }

  /// 🌍 زبان کا لوکل نام واپس کرے (SnackBar وغیرہ میں دکھانے کے لیے)
  static String getNativeLanguageName(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return 'اردو';
      case 'arabic':
        return 'العربية';
      default:
        return 'English';
    }
  }

  /// 🧠 AI-Generated Data کا لیبل (اختیاری استعمال کے لیے)
  static String getAISectionLabel(String aiName, String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return 'AI ماڈیول: $aiName';
      case 'arabic':
        return 'نظام الذكاء الاصطناعي: $aiName';
      default:
        return 'AI Module: $aiName';
    }
  }
}
