import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

/// 🌐 Language Utility — Supports Urdu, Arabic, and English
class LanguageUtils {
  // ✅ تمام سپورٹڈ زبانوں کی معلومات
  static List<Map<String, dynamic>> getSupportedLanguages() {
    return [
      {
        'code': 'english',
        'name': 'English',
        'nativeName': 'English',
        'flag': '🇺🇸',
        'color': 0xFF2196F3, // Blue
        'font': 'OpenSans',
      },
      {
        'code': 'urdu',
        'name': 'Urdu',
        'nativeName': 'اردو',
        'flag': '🇵🇰',
        'color': 0xFF4CAF50, // Green
        'font': 'NotoNastaliqUrdu',
      },
      {
        'code': 'arabic',
        'name': 'Arabic',
        'nativeName': 'العربية',
        'flag': '🇸🇦',
        'color': 0xFFFF9800, // Orange
        'font': 'Amiri',
      },
    ];
  }

  // ✅ زبان کے کوڈ سے readable نام حاصل کریں
  static String getLanguageName(String code) {
    return getSupportedLanguages()
            .firstWhere((lang) => lang['code'] == code, orElse: () => {'name': 'English'})['name'] ??
        'English';
  }

  // ✅ زبان کا Native نام (جیسے اردو، العربية)
  static String getNativeLanguageName(String code) {
    return getSupportedLanguages()
            .firstWhere((lang) => lang['code'] == code, orElse: () => {'nativeName': 'English'})['nativeName'] ??
        'English';
  }

  // ✅ PDF اور UI Headers کے لیے ترجمہ شدہ مواد
  static Map<String, String> getPDFHeaders(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return {
          'title': 'طبی تحقیقاتی رپورٹ',
          'topic': 'موضوع',
          'date': 'تاریخ',
          'hypothesis': 'تحقیقی مفروضہ',
          'methodology': 'طریقہ کار / تجرباتی عمل',
          'labResults': 'لیبارٹری نتائج',
          'conclusion': 'نتیجہ اور مشاہدات',
          'footer': 'یہ رپورٹ مصنوعی ذہانت کے میڈیکل ریسرچ سسٹم کے ذریعے تیار کی گئی ہے۔',
        };

      case 'arabic':
        return {
          'title': 'تقرير البحث الطبي',
          'topic': 'الموضوع',
          'date': 'التاريخ',
          'hypothesis': 'الفرضية البحثية',
          'methodology': 'المنهجية والتجارب',
          'labResults': 'نتائج المختبر',
          'conclusion': 'الاستنتاج والملاحظات',
          'footer': 'تم إنشاء هذا التقرير بواسطة نظام البحث الطبي بالذكاء الاصطناعي.',
        };

      default:
        return {
          'title': 'MEDICAL RESEARCH REPORT',
          'topic': 'TOPIC',
          'date': 'DATE',
          'hypothesis': 'RESEARCH HYPOTHESIS',
          'methodology': 'METHODOLOGY / EXPERIMENTAL PROCESS',
          'labResults': 'LAB RESULTS',
          'conclusion': 'CONCLUSION & OBSERVATIONS',
          'footer': 'Generated by AI Medical Research System.',
        };
    }
  }

  // ✅ تاریخ کو زبان کے لحاظ سے فارمیٹ کریں
  static String formatDate(DateTime date, String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return DateFormat('dd MMMM yyyy', 'ur').format(date); // مثلاً: 4 نومبر 2025
      case 'arabic':
        return DateFormat('dd MMMM yyyy', 'ar').format(date); // مثلاً: 4 نوفمبر 2025
      default:
        return DateFormat('dd MMMM yyyy', 'en').format(date); // e.g. 4 November 2025
    }
  }

  // ✅ Text Direction (RTL / LTR) — UI میں استعمال کیلئے
  static TextDirection getTextDirection(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
      case 'arabic':
        return TextDirection.rtl;
      default:
        return TextDirection.ltr;
    }
  }

  // ✅ فونٹ فیملی (UI اور PDF دونوں کے لیے)
  static String getFontFamily(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return 'NotoNastaliqUrdu';
      case 'arabic':
        return 'Amiri';
      default:
        return 'OpenSans';
    }
  }

  // ✅ رنگ اور فلیگ آسانی سے حاصل کرنے کیلئے
  static Color getLanguageColor(String language) {
    final lang = getSupportedLanguages()
        .firstWhere((e) => e['code'] == language, orElse: () => {'color': 0xFF2196F3});
    return Color(lang['color']);
  }

  static String getFlag(String language) {
    final lang = getSupportedLanguages()
        .firstWhere((e) => e['code'] == language, orElse: () => {'flag': '🌐'});
    return lang['flag'];
  }

  // ✅ زبان کو Normalize کرو
  static String normalize(String input) {
    return input.toLowerCase().trim();
  }
}
