import 'package:flutter/material.dart';

/// 🌐 Language Utility — Supports Urdu, Arabic, and English
class LanguageUtils {
  // ✅ تمام سپورٹڈ زبانوں کی معلومات
  static List<Map<String, dynamic>> getSupportedLanguages() {
    return [
      {
        'code': 'english',
        'name': 'English',
        'nativeName': 'English',
        'flag': '🇺🇸',
        'color': 0xFF2196F3, // Blue
      },
      {
        'code': 'urdu', 
        'name': 'Urdu',
        'nativeName': 'اردو',
        'flag': '🇵🇰',
        'color': 0xFF4CAF50, // Green
      },
      {
        'code': 'arabic',
        'name': 'Arabic', 
        'nativeName': 'العربية',
        'flag': '🇸🇦',
        'color': 0xFFFF9800, // Orange
      },
    ];
  }

  // ✅ زبان کے کوڈ سے readable نام حاصل کریں
  static String getLanguageName(String code) {
    return getSupportedLanguages()
            .firstWhere((lang) => lang['code'] == code, orElse: () => {'name': 'English'})['name'] ??
        'English';
  }

  // ✅ زبان کا Native نام (جیسے اردو، العربية)
  static String getNativeLanguageName(String code) {
    return getSupportedLanguages()
            .firstWhere((lang) => lang['code'] == code, orElse: () => {'nativeName': 'English'})['nativeName'] ??
        'English';
  }

  // ✅ PDF اور UI Headers کے لیے ترجمہ شدہ مواد
  static Map<String, String> getPDFHeaders(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
        return {
          'title': 'طبی تحقیقاتی رپورٹ',
          'topic': 'موضوع',
          'date': 'تاریخ', 
          'hypothesis': 'تحقیقی مفروضہ',
          'methodology': 'طریقہ کار',
          'labResults': 'لیبارٹری نتائج',
          'conclusion': 'نتیجہ',
          'footer': 'AI میڈیکل ریسرچ سسٹم کے ذریعے تیار کردہ',
        };

      case 'arabic':
        return {
          'title': 'تقرير البحث الطبي',
          'topic': 'الموضوع',
          'date': 'التاريخ',
          'hypothesis': 'الفرضية',
          'methodology': 'المنهجية', 
          'labResults': 'نتائج المختبر',
          'conclusion': 'الاستنتاج',
          'footer': 'تم إنشاؤها بواسطة نظام البحث الطبي بالذكاء الاصطناعي',
        };

      default:
        return {
          'title': 'MEDICAL RESEARCH REPORT',
          'topic': 'TOPIC',
          'date': 'DATE',
          'hypothesis': 'HYPOTHESIS',
          'methodology': 'METHODOLOGY',
          'labResults': 'LAB RESULTS', 
          'conclusion': 'CONCLUSION',
          'footer': 'Generated by AI Medical Research System',
        };
    }
  }

  // ✅ تاریخ کو زبان کے لحاظ سے فارمیٹ کریں (Simplified)
  static String formatDate(DateTime date, String language) {
    // Simple date format - intl package کے بغیر
    return '${date.day}/${date.month}/${date.year}';
  }

  // ✅ Text Direction (RTL / LTR) — UI میں استعمال کیلئے
  static TextDirection getTextDirection(String language) {
    switch (language.toLowerCase()) {
      case 'urdu':
      case 'arabic':
        return TextDirection.rtl;
      default:
        return TextDirection.ltr;
    }
  }

  // ✅ رنگ اور فلیگ آسانی سے حاصل کرنے کیلئے
  static Color getLanguageColor(String language) {
    final lang = getSupportedLanguages()
        .firstWhere((e) => e['code'] == language, orElse: () => {'color': 0xFF2196F3});
    return Color(lang['color'] as int);
  }

  static String getFlag(String language) {
    final lang = getSupportedLanguages()
        .firstWhere((e) => e['code'] == language, orElse: () => {'flag': '🌐'});
    return lang['flag'] as String;
  }
}
